---
- name: Generate Private Key
  openssl_privatekey:
    path: "{{ certs_dir }}/{{ cert_key_file }}"
    size: "{{ cert_key_size | default('4096', true) }}"
    type: "{{ cert_key_type | default('RSA', true) }}"

