---
- name: Generate The CSR for the certificate
  community.crypto.openssl_csr:
    path: "{{ certs_dir }}/{{ cert_csr_file }}"
    privatekey_path: "{{ certs_dir }}/{{ cert_key_file }}"
    country_name: "{{ cert_country | default('US', true) }}"
    locality_name: "{{ cert_locality | default('Denver', true) }}"
    state_or_province_name: "{{ cert_state | default('CO', true) }}"
    organization_name: "{{ cert_org | default('Red Hat', true) }}"
    organizational_unit_name: "{{ cert_org_unit | default('OpenShift Container Platform', true) }}"
    common_name: "{{ cert_cm }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
      - keyCertSign
    key_usage_critical: true
    subject_alt_name: "{{ cert_san }}"
  when:
    - not is_ca_csr is defined or not is_ca_csr | bool 
  register: csr_created

- name: Generate The CSR for the CA certificate
  community.crypto.openssl_csr:
    path: "{{ certs_dir }}/{{ cert_csr_file }}"
    privatekey_path: "{{ certs_dir }}/{{ cert_key_file }}"
    country_name: "{{ cert_country | default('US', true) }}"
    locality_name: "{{ cert_locality | default('Denver', true) }}"
    state_or_province_name: "{{ cert_state | default('CO', true) }}"
    organization_name: "{{ cert_org | default('Red Hat', true) }}"
    organizational_unit_name: "{{ cert_org_unit | default('OpenShift Container Platform', true) }}"
    common_name: "{{ cert_cm_ca }}"
    key_usage:
      - digitalSignature
      - cRLSign
      - keyCertSign
    subject_alt_name: "{{ ca_san }}"
    basic_constraints:
      - CA:TRUE
  when:
    - is_ca_csr is defined 
    - is_ca_csr | bool 
  register: ca_csr_created

